# Generated by Django 4.2.11 on 2024-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='display_image',
            field=models.BooleanField(default=True),
        ),
    ]
