# Generated by Django 4.2.11 on 2024-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_discounted_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
