# Generated by Django 4.2.11 on 2024-04-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_subcategory_image_category_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='email',
            new_name='phone',
        ),
    ]
